### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by scyv** [scyv/scrum-poker#22]
Exception in template helper: TypeError: Cannot read properties of undefined (reading 'name')
    at k (https://poker.digital-scrum.de/1f81382d2aafc977e08887e888a5e87e2780322a.js?meteor_js_resource=true:208:60434)
    at Object.story (https://poker.digital-scrum.de/1f81382d2aafc977e08887e888a5e87e2780322a.js?meteor_js_resource=true:208:61912)
    at https://poker.digital-scrum.de/1f81382d2aafc977e08887e888a5e87e2780322a.js?meteor_js_resource=true:160:31940
    at https://poker.digital-scrum.de/1f81382d2aafc977e08887e888a5e87e2780322a.js?meteor_js_resource=true:160:17340
    at https://poker.digital-scrum.de/1f81382d2aafc977e08887e888a5e87e2780322a.js?meteor_js_resource=true:160:32574
    at Function.c._withTemplateInstanceFunc (https://poker.digital-scrum.de/1f81382d2aafc977e08887e888a5e87e2780322a.js?meteor_js_resource=true:160:38718)
    at https://poker.digital-scrum.de/1f81382d2aafc977e08887e888a5e87e2780322a.

**Comment by scyv** [comment]
This happens when a story is deleted while a participant has opened the story

**Comment by scyv** [comment]
und noch:

Exception while invoking method 'setStory' TypeError: Cannot read property 'participants' of undefined
    at MethodInvocation.setStory (imports/methods.js:96:59)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)
    at packages/ddp-server/livedata_server.js:769:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:767:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:765:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:739:23)
